### ISSUE TITLE
3. BACKEND - MODELS

### ISSUE THREAD

**Issue by CYCBrian** [karina-yuk/WorkoutBuddy-Match#4]
Create models for :

index.js:
ASSOCIATIONS:

CITY belong to USER
USER has one CITY

GYM belongs to many CITY
CITY has Many GYM

USER has one GYM
GYM belongs to many USER

USER has one WORKOUT
WORKOUT belong to many USER

PROFILEPIC belongs to USER
USER has one PROFILEPIC

user
city
gym
workout
profilepic

**Comment by dannadlerp** [comment]
partially finished. just created each tables' .js file in the models folder
